#!/usr/bin/env python
# coding: utf-8

#  Feature_Extraction

# #### Feature extraction is a fundamental process in deep learning and machine learning that involves transforming raw data into a set of meaningful attributes or features that can enhance model performance.
 
# ##### Convolutional Neural Networks (CNNs): Automatically learn hierarchical representations of images, detecting basic elements in early layers and complex objects in deeper layers.


# import Libraries

import numpy as np
import time
import PIL.Image as Image
import matplotlib.pylab as plt
import tensorflow as tf
import tensorflow_hub as hub
import datetime


# Downloads a dataset of flower photos from a URL, 
# caches it locally, and extracts the contents.

import pathlib

data_file = tf.keras.utils.get_file(
  'flower_photos.tgz',
  'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
  cache_dir='.',
   extract=True)


# cache_dir='.',   # The directory where the downloaded file will be cached.
# extract=True  # Specifies whether to extract the downloaded archive.

data_root = pathlib.Path(data_file).with_suffix('')
data_root
# used to remove the file extension from the path of the downloaded dataset.


# convert to string
str(data_root)


# define images form factors
batch_size = 32
img_height = 224
img_width = 224


# prepare train dataset

train_ds = tf.keras.utils.image_dataset_from_directory(
  str(data_root),
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size,
    
  #label_mode = 'categorical'
)



# prepare validation dataset

val_ds = tf.keras.utils.image_dataset_from_directory(
  str(data_root),
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size,
    #label_mode = 'categorical'
)


# print classes

class_names = np.array(train_ds.class_names)
print(class_names)

# print image in batches with label
for image_batch, labels_batch in val_ds:
  print(image_batch)
  print(labels_batch)
  break


# Create a normalization layer that rescales pixel values to the range [0, 1]
normalization_layer = tf.keras.layers.Rescaling(1./255)

train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y)) # Where x—images, y—labels.
val_ds = val_ds.map(lambda x, y: (normalization_layer(x), y)) 
# Where x—images, y—labels.

# Apply the normalization layer to the training, validation dataset
# The map function applies the normalization to each image (x) while keeping the labels (y) unchanged.


for image_batch, labels_batch in val_ds:
  print(image_batch)
  print(labels_batch)
  break
    
# Iterate through the validation dataset (val_ds) to access batches of images and their corresponding labels
# Print the current batch of images with corresponding labels.


# Define AUTOTUNE to dynamically adjust the number of parallel calls based on available CPU
AUTOTUNE = tf.data.AUTOTUNE

# Optimize the training dataset (train_ds) for performance
# .cache() stores the dataset in memory after the first epoch
# .prefetch() overlaps data preprocessing and model execution
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)

# Optimize the validation dataset (val_ds) for performance
# .cache() stores the dataset in memory after the first epoch
# .prefetch() overlaps data preprocessing and model execution
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)


# Create a Keras Layer from a pre-trained feature extractor (Inception V3)

feature_extractor_layer = hub.KerasLayer(
    "https://www.kaggle.com/models/google/inception-v3/TensorFlow2/tf2-preview-feature-vector/4",  # URL of the pre-trained feature extractor
    input_shape=(224, 224, 3),  # Specify the expected input shape: 224x224 pixels with 3 color channels (RGB)
    trainable=False  # Freeze the weights of the pre-trained layer to prevent them from being updated during training
)
# Inception V3 is a widely used convolutional neural network architecture known for its efficiency and accuracy in image classification tasks.
# check shape

image_batch.shape
labels_batch.shape

# Pass the batch of images through the feature extractor layer to obtain feature representations
feature_batch = feature_extractor_layer(image_batch)
print(feature_batch.shape)

# Print the shape of the extracted features for the current batch of images
# This helps in understanding the dimensionality of the features generated by the feature extractor


# train model with custom output layer
num_classes = len(class_names)

model = tf.keras.Sequential([
  feature_extractor_layer,
  tf.keras.layers.Dense(512,activation='relu'),
  tf.keras.layers.Dense(5,activation='softmax')
])

model.summary()


# compile model

model.compile(
  optimizer=tf.keras.optimizers.Adam(),
  loss=tf.keras.losses.SparseCategoricalCrossentropy(),
  metrics=['accuracy'])

# while our dataset is labelled dataset, we use SparseCategoricalCrossentropy.

# train model
NUM_EPOCHS = 10
history = model.fit(train_ds,
                    validation_data=val_ds,
                    epochs=NUM_EPOCHS)

# The model is trained for a specified number of epochs (NUM_EPOCHS) using the training dataset (train_ds)
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(NUM_EPOCHS)

plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()


# predict i=one image batch 

predicted_batch = model.predict(image_batch)
predicted_batch


# Compute the predicted class IDs by finding the index of the maximum value along the last axis (axis=-1)
# This is useful for multi-class classification where each entry in 'predicted_batch' corresponds to class probabilities.

predicted_id = tf.math.argmax(predicted_batch, axis=-1)

# Display the predicted class IDs for the current batch
predicted_id

# convert to numpy
labels_batch = labels_batch.numpy()
print('labels_batch',labels_batch)


# convert to numpy 
predicted_id = predicted_id.numpy()
print('predicted_id', predicted_id)
# Display the true labels and predicted class IDs for comparison